CREATE DATABASE IF NOT EXISTS DB_NAME ;
CREATE USER IF NOT EXISTS 'DB_USER'@'%' IDENTIFIED BY 'DB_PASSWORD' ;
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER'@'%' IDENTIFIED BY 'DB_PASSWORD' ;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345' ;
ALTER USER 'mysql'@'localhost' IDENTIFIED BY '12345' ;
FLUSH PRIVILEGES;